set(APPLICATIONS_SRC_DIR "${CMAKE_SOURCE_DIR}/apps")
file(GLOB APPLICATIONS RELATIVE ${APPLICATIONS_SRC_DIR} "${APPLICATIONS_SRC_DIR}/*")

foreach(APPLICATION ${APPLICATIONS})
    set(APPLICATION_DIR "${APPLICATIONS_SRC_DIR}/${APPLICATION}/")
    if ( NOT EXISTS "${APPLICATION_DIR}/.ignore" )
         add_subdirectory(${APPLICATION_DIR})
    endif()
endforeach()
